import React, { useState } from 'react';
import {
  CalendarClock,
  Droplets,
  Zap,
  CheckCircle2,
  Clock,
  Filter,
  Download,
  Share2,
  Sprout,
  ArrowRight,
  Info,
  HelpCircle,
  Sun,
  CloudRain,
  ShieldCheck,
} from 'lucide-react';
import { ScheduleItem } from '../types.js';
import { useViewMode } from '../context/ViewModeContext.js';

interface SchedulePageProps {
  schedule: ScheduleItem[];
  onExportCsv: () => void;
}

export const SchedulePage: React.FC<SchedulePageProps> = ({
  schedule,
  onExportCsv,
}) => {
  const { isSimple } = useViewMode();
  const [filterDecision, setFilterDecision] = useState<'ALL' | 'Irrigate' | 'Delay'>('ALL');
  const [selectedSlot, setSelectedSlot] = useState<string>('ALL');

  const filteredSchedule = schedule.filter((item) => {
    const matchesDecision = filterDecision === 'ALL' || item.decision === filterDecision;
    const matchesSlot = selectedSlot === 'ALL' || item.timeSlot === selectedSlot;
    return matchesDecision && matchesSlot;
  });

  const slots = ['06:00 - 08:00', '08:00 - 10:00', '10:00 - 12:00', '16:00 - 18:00'];

  const irrigateItems = schedule.filter((s) => s.decision === 'Irrigate');
  const delayItems = schedule.filter((s) => s.decision === 'Delay');
  const totalWater = irrigateItems.reduce((acc, s) => acc + s.waterLiters, 0);

  const getPriorityBadge = (p: string) => {
    switch (p) {
      case 'HIGH':
        return <span className="px-2 py-0.5 text-[10px] font-bold rounded-full bg-rose-50 text-rose-700 border border-rose-200">HIGH</span>;
      case 'MEDIUM':
        return <span className="px-2 py-0.5 text-[10px] font-bold rounded-full bg-amber-50 text-amber-700 border border-amber-200">MEDIUM</span>;
      default:
        return <span className="px-2 py-0.5 text-[10px] font-bold rounded-full bg-slate-100 text-slate-600 border border-slate-200">LOW</span>;
    }
  };

  return (
    <div className="p-6 space-y-6 max-w-7xl mx-auto">
      {/* Page Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div>
          <h2 className="text-xl font-bold text-slate-900 tracking-tight flex items-center gap-2">
            <CalendarClock className="w-5 h-5 text-cyan-600" />
            {isSimple ? 'Today’s Irrigation Plan & Timetable' : 'Optimized Irrigation Timeline & Explainable Dispatch Schedule'}
          </h2>
          <p className="text-xs text-slate-500">
            {isSimple
              ? 'Clear breakdown of which fields get water, at what exact hour, and the reason why.'
              : 'Hourly allocation plan generated by the QUBO solver. Matches soil deficits to low-tariff solar pumping windows.'}
          </p>
        </div>

        <div className="flex items-center space-x-3">
          <button
            id="btn-export-schedule"
            onClick={onExportCsv}
            className="px-3 py-1.5 bg-white hover:bg-slate-50 text-slate-700 border border-slate-200 rounded-lg text-xs font-semibold shadow-xs transition-colors flex items-center space-x-1.5"
          >
            <Download className="w-3.5 h-3.5 text-slate-500" />
            <span>Export Schedule CSV</span>
          </button>
        </div>
      </div>

      {/* Plain-English 4-Question Summary Card */}
      <div className="bg-gradient-to-r from-cyan-50 via-white to-emerald-50 rounded-2xl p-5 border border-cyan-200/80 shadow-xs space-y-3">
        <div className="flex items-center justify-between">
          <h3 className="text-xs font-bold uppercase tracking-wider text-cyan-900 flex items-center gap-1.5">
            <HelpCircle className="w-4 h-4 text-cyan-600" />
            Quick Answers to Today’s Irrigation Plan
          </h3>
          <span className="text-[11px] text-cyan-700 font-semibold">Live Algorithm Output</span>
        </div>

        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-3 text-xs">
          <div className="bg-white/90 p-3 rounded-xl border border-cyan-100 shadow-xs">
            <div className="text-slate-500 text-[11px]">1. Who Gets Water?</div>
            <div className="font-bold text-slate-900 mt-1 text-sm">
              {irrigateItems.length} Fields Approved
            </div>
            <div className="text-[11px] text-slate-500 mt-0.5 truncate">
              {irrigateItems.map((i) => i.fieldId).join(', ') || 'None'}
            </div>
          </div>

          <div className="bg-white/90 p-3 rounded-xl border border-cyan-100 shadow-xs">
            <div className="text-slate-500 text-[11px]">2. Best Time to Water?</div>
            <div className="font-bold text-amber-900 mt-1 text-sm flex items-center gap-1">
              <Sun className="w-3.5 h-3.5 text-amber-500" />
              06:00 – 08:00 AM
            </div>
            <div className="text-[11px] text-slate-500 mt-0.5">
              100% Free Solar Electricity
            </div>
          </div>

          <div className="bg-white/90 p-3 rounded-xl border border-cyan-100 shadow-xs">
            <div className="text-slate-500 text-[11px]">3. Total Water Released?</div>
            <div className="font-bold text-emerald-900 mt-1 text-sm flex items-center gap-1">
              <Droplets className="w-3.5 h-3.5 text-emerald-600" />
              {totalWater.toLocaleString()} Liters
            </div>
            <div className="text-[11px] text-emerald-700 mt-0.5">
              Zero wasteful runoff
            </div>
          </div>

          <div className="bg-white/90 p-3 rounded-xl border border-cyan-100 shadow-xs">
            <div className="text-slate-500 text-[11px]">4. Who is Delayed &amp; Why?</div>
            <div className="font-bold text-slate-900 mt-1 text-sm flex items-center gap-1">
              <CloudRain className="w-3.5 h-3.5 text-cyan-600" />
              {delayItems.length} Fields Delayed
            </div>
            <div className="text-[11px] text-slate-500 mt-0.5 truncate">
              Rain forecast / moist soil
            </div>
          </div>
        </div>
      </div>

      {/* Timeline Slots Visualizer */}
      <div className="bg-white rounded-2xl p-6 border border-slate-200 shadow-sm space-y-4">
        <h3 className="font-bold text-slate-800 text-sm flex items-center gap-2">
          <Clock className="w-4 h-4 text-cyan-600" />
          24-Hour Canal Dispatch Slots
        </h3>

        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
          {slots.map((slot) => {
            const itemsInSlot = schedule.filter((s) => s.timeSlot === slot && s.decision === 'Irrigate');
            const totalSlotWater = itemsInSlot.reduce((sum, s) => sum + s.waterLiters, 0);

            return (
              <div
                key={slot}
                onClick={() => setSelectedSlot(selectedSlot === slot ? 'ALL' : slot)}
                className={`p-4 rounded-xl border transition-all cursor-pointer ${
                  selectedSlot === slot
                    ? 'bg-cyan-50/80 border-cyan-400 ring-2 ring-cyan-200 shadow-sm'
                    : 'bg-slate-50 border-slate-200 hover:border-slate-300'
                }`}
              >
                <div className="flex justify-between items-center mb-2">
                  <span className="text-xs font-bold text-slate-800 font-mono">{slot}</span>
                  <span className="text-[10px] uppercase font-semibold px-2 py-0.5 rounded-full bg-cyan-100 text-cyan-800">
                    {slot.includes('06:00') ? 'Solar Window' : slot.includes('08:00') ? 'Morning Slot' : 'Standard'}
                  </span>
                </div>

                <div className="text-lg font-bold text-slate-900 font-mono">
                  {totalSlotWater.toLocaleString()} <span className="text-xs font-normal text-slate-500">L</span>
                </div>

                <div className="text-[11px] text-slate-500 mt-1">
                  {itemsInSlot.length > 0 ? (
                    <span>
                      Fields:{' '}
                      <strong className="text-cyan-700">
                        {itemsInSlot.map((item) => item.fieldId).join(', ')}
                      </strong>
                    </span>
                  ) : (
                    <span className="text-slate-400 italic">No fields scheduled</span>
                  )}
                </div>
              </div>
            );
          })}
        </div>
      </div>

      {/* Filter Toolbar */}
      <div className="bg-white p-4 rounded-xl border border-slate-200 shadow-xs flex flex-col sm:flex-row items-center justify-between gap-3">
        <div className="flex items-center gap-2 text-xs">
          <Filter className="w-3.5 h-3.5 text-slate-400" />
          <span className="text-slate-500 font-medium">Filter Decision:</span>
          <div className="flex gap-1 bg-slate-100 p-1 rounded-lg">
            {(['ALL', 'Irrigate', 'Delay'] as const).map((mode) => (
              <button
                key={mode}
                onClick={() => setFilterDecision(mode)}
                className={`px-3 py-1 rounded-md text-xs font-semibold transition-colors ${
                  filterDecision === mode
                    ? 'bg-white text-slate-800 shadow-xs'
                    : 'text-slate-500 hover:text-slate-800'
                }`}
              >
                {mode === 'ALL' ? 'All Decisions' : mode}
              </button>
            ))}
          </div>
        </div>

        {selectedSlot !== 'ALL' && (
          <div className="flex items-center gap-2 text-xs text-cyan-700 bg-cyan-50 px-3 py-1 rounded-lg border border-cyan-200">
            <span>Filtered by Slot: <strong>{selectedSlot}</strong></span>
            <button
              onClick={() => setSelectedSlot('ALL')}
              className="text-cyan-900 hover:underline font-semibold ml-1"
            >
              Clear
            </button>
          </div>
        )}
      </div>

      {/* Main Schedule Table */}
      <div className="bg-white rounded-2xl border border-slate-200 overflow-hidden shadow-xs">
        <div className="overflow-x-auto">
          <table className="w-full text-left text-xs text-slate-700">
            <thead className="bg-slate-50 border-b border-slate-200 text-slate-500 font-semibold uppercase">
              <tr>
                <th className="px-4 py-3">Time Slot</th>
                <th className="px-4 py-3">Field ID</th>
                <th className="px-4 py-3">Crop Type</th>
                <th className="px-4 py-3">Water Allocated</th>
                <th className="px-4 py-3">Canal / Source</th>
                <th className="px-4 py-3">Pump Unit</th>
                <th className="px-4 py-3">Priority</th>
                <th className="px-4 py-3">Decision</th>
                <th className="px-4 py-3">Explainability Reason</th>
                <th className="px-4 py-3 text-right">Cost / CO2</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-100">
              {filteredSchedule.map((item) => {
                const isIrrigate = item.decision === 'Irrigate';

                return (
                  <tr
                    key={item.id}
                    className={`transition-colors ${
                      isIrrigate ? 'hover:bg-slate-50/80' : 'bg-slate-50/40 text-slate-400 hover:bg-slate-50'
                    }`}
                  >
                    <td className="px-4 py-3.5 font-mono font-bold text-slate-800">
                      {item.timeSlot !== '—' ? item.timeSlot : <span className="text-slate-400">—</span>}
                    </td>
                    <td className="px-4 py-3.5 font-bold text-slate-900">
                      <div className="flex items-center space-x-1.5">
                        <span className="w-6 h-6 rounded-md bg-cyan-100 text-cyan-800 flex items-center justify-center font-bold text-[11px]">
                          {item.fieldId}
                        </span>
                        <span className="font-normal text-slate-600 text-[11px] truncate max-w-[110px]">
                          {item.fieldName}
                        </span>
                      </div>
                    </td>
                    <td className="px-4 py-3.5 font-semibold text-emerald-700">{item.crop}</td>
                    <td className="px-4 py-3.5 font-mono">
                      {isIrrigate ? (
                        <span className="font-bold text-slate-900">
                          {item.waterLiters.toLocaleString()} L
                        </span>
                      ) : (
                        <span className="text-slate-400">0 L</span>
                      )}
                    </td>
                    <td className="px-4 py-3.5 text-slate-600">{item.canalName}</td>
                    <td className="px-4 py-3.5 text-slate-600">{item.pumpName}</td>
                    <td className="px-4 py-3.5">{getPriorityBadge(item.priority)}</td>
                    <td className="px-4 py-3.5">
                      {isIrrigate ? (
                        <span className="px-2.5 py-1 text-[11px] font-bold rounded-full bg-emerald-100 text-emerald-800 border border-emerald-200">
                          Irrigate
                        </span>
                      ) : (
                        <span className="px-2.5 py-1 text-[11px] font-bold rounded-full bg-slate-200 text-slate-700">
                          Delay
                        </span>
                      )}
                    </td>
                    <td className="px-4 py-3.5 text-[11px] text-slate-600 max-w-xs leading-relaxed">
                      {item.reason}
                    </td>
                    <td className="px-4 py-3.5 text-right font-mono">
                      {isIrrigate ? (
                        <div>
                          <div className="font-bold text-purple-700">₹{item.energyCost}</div>
                          <div className="text-[10px] text-slate-400">{item.co2Grams}g CO2</div>
                        </div>
                      ) : (
                        <span className="text-slate-400">₹0</span>
                      )}
                    </td>
                  </tr>
                );
              })}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
};
